
server:
  port: 10030
spring:
  devtools:
    restart:
      enabled: false
    add-properties: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/dragon?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    # druid???
    druid:
      initial-size: 5                                               #?????
      min-idle: 10                                                  #?????
      max-active: 20                                                #?????
      max-wait: 9000
      min-evictable-idle-time-millis: 300000                        #???????????????????
      time-between-eviction-runs-millis: 60000                      #????????????????????????
      filters: stat,wall                                            #???????stat-?????log4j-???wall-???
      validation-query: SELECT 1  FROM DUAL                         #?????????SQL???????????????
      test-on-borrow: true                                          #???????validationQuery???????????true,????????
      test-on-return: true                                          #???????validationQuery???????????true,????????
      test-while-idle: true                                         #?????????????timeBetweenEvictionRunsMillis,??validationQuery???????????false,ji??????????
      stat-view-servlet:
        enabled: true                                               #????StatViewServlet
        allow: 127.0.0.1                                            #?????? ??????127.0.0.1
        deny: 192.168.102.58                                        #?????? ???
        login-username: admin                                       #?????? ????
        login-password: admin                                       #?????? ????
        reset-enable: false
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true                                             #????FilterStat,??true
          log-slow-sql: true                                        #?????sql?????false
          slow-sql-millis: 5000                                     #?sql??????3000?????
          merge-sql: false                                          #???????????????false

  redis:
    host: localhost
    port: 6379
    #Redis?????????????
    password:
    timeout: 30000                                                  #??????????
    jedis:
      pool:
        max-active: 8                                               #????????????????????
        max-wait: -1                                                #???????????????????????
        max-idle: 8                                                 #???????????
        min-idle: 0                                                 #???????????

#mybatis??
mybatis:
  check-config-location: true
  # mybatis?????? ?mybatis????????
  config-location: "classpath:mybatis/mybatis-config.xml"
  #??xml??
  mapper-locations: "classpath:mybatis/mapper/*Mapper.xml"
  type-aliases-package: "com.example.springbootlog4j.gui.*.entity"

